algorithm: voxel_map
filter_size_scan_m: 0.5
map_voxel_size_m: 0.25
max_layer: 2
layer_point_sizes: [5, 5]
max_points_per_voxel: 100
max_iterations: 4
min_eigenvalue_ratio: 0.01
range_noise_m: 0.02
angle_noise_deg: 0.05
