algorithm: faster_lio
filter_size_scan_m: 0.2
filter_size_map_m: 0.2
map_voxel_size_m: 0.5
max_iterations: 4
estimate_extrinsics: false
gyroscope_noise: 0.1
accelerometer_noise: 0.1
gyroscope_bias_noise: 0.0001
accelerometer_bias_noise: 0.0001
ivox_nearby_type: 18
